#
# Copyright (C) 2014
# Jeff Kent <jeff@jkent.net>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	:= mini210.o
obj-y	+= lowlevel_init.o
obj-$(CONFIG_CMD_USB_MASS_STORAGE)   += ../../samsung/common/ums.o
